--- 
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - debug:
      var: instance_id
  - name: Add vm to load balancer
    local_action: ec2_elb
    args:
      instance_id: "{{ instance_id }}"
      ec2_elbs: "{{ load_balancer }}"
      state: present
      region: "{{ region }}"
