---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - debug:
      var: instance_id
  - name: set the facts
    debug:
      msg: "{{ hostvars['localhost'].keys() }}"
  - name: Add vm to load balancer
    local_action: ec2_elb
    args:
      instance_id: "{{ instance_id }}"
      ec2_elbs: "{{ lb_name }}"
      state: present
      region: "{{ region }}"
    register: lb_added
  - debug: 
      var: lb_added
