- name: Get ELB
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - syncrou.manageiq-automate
  tasks:
  - name: "Get Attributes"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_attribute:
        object: "root"
        attribute: "elb_name"
    register: elb_name
  - debug:
      var: elb_name
  - name: "Get Region"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_attribute:
        object: "root"
        attribute: "region"
    register: region
  - debug:
      var: region
  - name: "Get Instance ID"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_attribute:
        object: "root"
        attribute: "instance_id"
    register: instance_id
  - debug:
      var: instance_id
- name: Add to the Load Balancer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Add vm to load balancer
    local_action: ec2_elb
    args:
      instance_id: "{{ instance_id }}"
      ec2_elbs: "{{ lb_name }}"
      state: present
      region: "{{ region }}"
    register: lb_added
    ignore_errors: yes
  - debug: 
      var: lb_added
