- name: create ELB and add an instance to ELB
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - debug:
      var: elb_name
  - debug:
      var: region
  - debug:
      var: availability_zone
  - debug:
      var: subnet_id
  - debug:
      var: elb_port
  - name: setup a simple load balancer
    ec2_elb_lb:
      name: "{{ elb_name }}"
      state: present
      region: "{{ region }}"
      subnets:
        - "{{ subnet_id }}"
      health_check:
          ping_protocol: http
          ping_port: 80
          ping_path: "/index.html"
          response_timeout: 5 
          interval: 30 
          unhealthy_threshold: 10
          healthy_threshold: 2
      listeners:
        - protocol: http
          load_balancer_port: "{{ elb_port }}"
          instance_port: "{{ elb_port }}"
    register: aws_elb
  - debug: 
      var: aws_elb
  - set_fact:
      lb_name={{ aws_elb.elb.name }}
      cacheable=yes
  - debug: 
      var: lb_name
  - name: Add vm to load balancer
    local_action: ec2_elb
    args:
      instance_id: "{{ instance_id }}"
      ec2_elbs: "{{ lb_name }}"
      state: present
      region: "{{ region }}"
    register: lb_added
    ignore_errors: yes
  - debug: 
      var: lb_added
