- name: create ELB
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - debug:
      var: elb_name
  - debug:
      var: region
  - debug:
      var: availability_zone
  - debug:
      var: elb_port
  - name: setup a simple load balancer
    ec2_elb_lb:
      name: "{{ elb_name }}"
      state: present
      region: "{{ region }}"
      zones:
        - "{{ availability_zone }}"
      listeners:
        - protocol: http
          load_balancer_port: "{{ elb_port }}"
          instance_port: "{{ elb_port }}"
    register: aws_elb
  - debug: 
      var: aws_elb
  - set_fact:
      lb_name={{ aws_elb.elb.name }}
  - debug: 
      var: lb_name
      
- name: Add to the Load Balancer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - debug:
      var: instance_id
  - debug: 
      var: hostvars['localhost']['ansible_facts']
  - name: set the facts 
    set_fact:
      lb_name: "{{ hostvars['localhost']['ansible_facts']['lb_name'] }}"
  - name: Add vm to load balancer
    local_action: ec2_elb
    args:
      instance_id: "{{ instance_id }}"
      ec2_elbs: "{{ lb_name }}"
      state: present
      region: "{{ region }}"
    register: lb_added
  - debug: 
      var: lb_added
