- name: create ELB
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - debug:
      var: elb_name
  - debug:
      var: region
  - debug:
      var: availability_zone
  - debug:
      var: elb_port
  - name: setup a simple load balancer
    ec2_elb_lb:
      name: "{{ elb_name }}"
      state: present
      region: "{{ region }}"
      zones:
        - "{{ availability_zone }}"
      listeners:
        - protocol: http
          load_balancer_port: "{{ elb_port }}"
          instance_port: "{{ elb_port }}"
    register: aws-elb
  - debug: 
      var: aws-elb
