- name: create ELB
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: setup a simple load balancer
      ec2_elb_lb:
        name: "{{ elb_name }}"
        state: present
        region: us-east-1
        zones:
          - us-east-1a
        listeners:
          - protocol: http
            load_balancer_port: "{{ elb_port }}"
            instance_port: "{{ elb_port }}"
      register: aws-elb
    - debug:
        var: aws-elb
