--- 
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Get Request Details
    uri: 
      method: GET
      status_code: 200
      url: "{{ manageiq.api_url }}/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
      validate_certs: false
      headers: 
        X-Auth-Token: "{{ manageiq.api_token }}"
    register: result
  - debug: msg="Result is:{{ result.stdout | to_json }}"
